"""
Options candidate generator: unifies deterministic template seeds with
creative LLM quantitative reasoning.
"""
from __future__ import annotations

import logging
from typing import List, Set
from brain_options.llm.adapter import LLMAdapter, clean_json_array
from brain_options.llm.prompts import OPTIONS_REASONING_PROMPT, OPTIONS_SYSTEM_PROMPT
from brain_options.specialist.templates import OptionCandidate, generate_template_candidates

log = logging.getLogger("brain_options.generator")


class OptionsGenerator:
    def __init__(self, llm_adapter: LLMAdapter):
        self.llm_adapter = llm_adapter
        self.evaluated_expressions: Set[str] = set()
        self._template_queue: list[OptionCandidate] = generate_template_candidates()

    def mark_evaluated(self, expression: str):
        self.evaluated_expressions.add(expression.strip())

    def is_evaluated(self, expression: str) -> bool:
        return expression.strip() in self.evaluated_expressions

    def get_template_batch(self, count: int = 5) -> list[OptionCandidate]:
        batch: list[OptionCandidate] = []
        while self._template_queue and len(batch) < count:
            cand = self._template_queue.pop(0)
            if not self.is_evaluated(cand.expression):
                batch.append(cand)
        return batch

    def get_llm_batch(self, count: int = 5) -> list[OptionCandidate]:
        prompt = OPTIONS_REASONING_PROMPT.format(n=count)
        raw_output = self.llm_adapter.generate(
            prompt=prompt,
            system_prompt=OPTIONS_SYSTEM_PROMPT,
            temperature=0.7,
        )
        if not raw_output:
            return []

        parsed = clean_json_array(raw_output)
        candidates: list[OptionCandidate] = []
        for item in parsed:
            expr = item.get("expression", "").strip()
            if not expr or self.is_evaluated(expr):
                continue
            candidates.append(
                OptionCandidate(
                    expression=expr,
                    archetype_name=item.get("archetype", "LLM Creative"),
                    hypothesis=item.get("hypothesis", "Generated by quantitative LLM."),
                    generation_source="llm",
                )
            )
        return candidates

    def get_next_batch(self, target_count: int = 10, template_ratio: float = 0.5) -> list[OptionCandidate]:
        template_count = max(1, int(target_count * template_ratio))
        llm_count = target_count - template_count

        candidates = self.get_template_batch(template_count)

        llm_candidates = self.get_llm_batch(llm_count)
        candidates.extend(llm_candidates)

        # Top-up if LLM returned fewer candidates
        if len(candidates) < target_count:
            shortfall = target_count - len(candidates)
            extra_templates = self.get_template_batch(shortfall)
            candidates.extend(extra_templates)

        return candidates
